---
- name: Configure Cobalt Strike Team Server
  hosts: teamserver
  become: yes
  vars_files:
    - group_variables/general.yaml
    - group_variables/vault.yaml
  roles:
    - common
    - teamserver

- name: Configure Nginx Redirectors
  hosts: redirectors
  become: yes
  vars_files:
    - group_variables/general.yaml
    - group_variables/vault.yaml
  roles:
    - common
    - redirector