---
- name: Configure Cobalt Strike Team Server
  hosts: team_server
  become: yes
  vars_files:
    - group_vars/general.yml
    - group_vars/vault.yml
  roles:
    - common
    - team_server

- name: Configure Nginx Redirectors
  hosts: redirectors
  become: yes
  vars_files:
    - group_vars/general.yml
    - group_vars/vault.yml
  roles:
    - common
    - redirector