---
all:
  children:
    team_server:
      hosts:
        team_server_1:
          ansible_host: <team_server_public_ip>
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/redteam-key
    redirectors:
      hosts:
        redirector_1:
          ansible_host: <redirector_1_public_ip>
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/redteam-key
        redirector_2:
          ansible_host: <redirector_2_public_ip>
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/redteam-key